export const LOADING_COMPLETED = 'LOADING_COMPLETED';
export const LOADING_FAILED = 'LOADING_FAILED,';
export const FETCH_PHOTOS_SUCCESS = 'FETCH_PHOTOS_SUCCESS';
export const FETCH_PHOTOS_FAIL = 'FETCH_PHOTOS_FAIL';
export const GET_USER_STATS_SUCCESS = 'GET_USER_STATS_SUCCESS';
export const GET_USER_STATS_FAIL = 'GET_USER_STATS_FAIL';
export const SET_USER_STATS_SUCCESS = 'SET_USER_STATS_SUCCESS';
export const SET_USER_STATS_FAIL = 'SET_USER_STATS_FAIL';
